### PR TITLE
[bug]:contest prefernce rank

### PR DESCRIPTION
**Pull request by jatingodnani**
#119 
@Nayaker check this  pr and tell me if it is working

### CODE REVIEW

**Comment by Nayaker** [comment]
@jatingodnani The friends that are displayed vanish when the page is refreshed. Wait I am attaching a video in a minute

**Comment by Nayaker** [comment]
https://github.com/Nayaker/AlgoListed/assets/93304796/77d34986-1dc7-46dd-9508-67ffdb45bf85

@jatingodnani Check this

**Comment by jatingodnani** [comment]
give some time,i am checking

**Comment by Nayaker** [comment]
No!
Buddy let's get on a call for a minute it's getting hard to explain you like this. 
@jatingodnani get on a meet with me : https://meet.google.com/hiz-swhq-vww?authuser=0 it will take a minute but clear all your doubts.

**Comment by Nayaker** [comment]
Screenshot 2023-10-06 at 6 29 45 PM

@jatingodnani

**Pull request closed without merging**
