### PR TITLE
bug:code-analysis

### PR DESCRIPTION
**Pull request by jatingodnani**
#119 @Nayaker check pr

### CODE REVIEW

**Comment by Nayaker** [comment]
Incredible, the PR is functioning just as expected! Excellent work @jatingodnani 🚀

**Comment by jatingodnani** [comment]
Add the functionality on input modal

**Comment by Nayaker** [comment]
https://meet.google.com/fhs-xquu-swi can you please join this min for 2 mins

**Comment by Nayaker** [comment]
@jatingodnani, there's a minor problem. You're currently unable to add users who haven't participated in a specific contest. For instance, if my friend @x hasn't participated in a contest, such as 'weekly-contest-5,' I should still be able to add them.

**Comment by jatingodnani** [comment]
Ok i will do that

**Comment by Nayaker** [comment]
It actually doesn't show anything after clicking add friend button

**Pull request merged**
