### PR TITLE
add test dark mode feature on landing page

### PR DESCRIPTION
**Pull request by nesyG**

### CODE REVIEW

**Comment by nesyG** [comment]
https://prnt.sc/KwdNgCV1RtO1
https://prnt.sc/Ey9TA4L70vv1
https://prnt.sc/lV7pW7zDmUph
https://prnt.sc/byhyE1pUgXqh
I still need to work on svg images and responsiveness. Let me know if this is something you had in mind on how the page should look.

**Comment by nesyG** [comment]
Thank you! 😃

**Comment by nesyG** [comment]
Hey @Nayaker, just letting you know I would like to keep working on this feature

**Comment by Nayaker** [comment]
@nesyG, I apologize for the delay, but I am currently taking my exams until March 7th. Additionally, there are a few things I need to address in the local environment before I can continue with the project.

Rest assured, I will merge your code as soon as possible, but it may take some time.

In the meantime, I would recommend working on this page - https://algolisted.com/coding-sheets/striver-sde-sheet - and attempting to implement a dark mode feature.

**Comment by nesyG** [comment]
@Nayaker , no problem and good luck with your tests! I will work on the suggested issue in the meantime :)

**Pull request closed without merging**
